# 这个检查叫什么名字
name: GitHub Actions Demo

# 什么时候触发
on: push

# 执行的任务
jobs: 
  check:
    name: 代码检查

    # 运行环境，目前支持:
    # ubuntu-latest，ubuntu-18.04或ubuntu-16.04
    # windows-latest，windows-2019或windows-2016
    # macOS-latest或macOS-10.14
    runs-on: ubuntu-latest

    # 执行的内容
    steps:
    - name: '安装依赖'
      env:
        TEST_ENV: laiyuanwen
      run: |
        echo $TEST_ENV

  build:
    name: 构建
    runs-on: ubuntu-latest
    # 执行的内容
    steps:
    - name: '构建'
      run: |
        cat README.md

  push:
    name: 上传产物

    runs-on: ubuntu-latest

    # needs 表示需要等build和check完成才执行
    needs: [check, build]

    # 执行的内容
    steps:
    - name: '安装依赖'
      run: |
        cat .gitignore

  